apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
        - image: yandex/clickhouse-server
          livenessProbe:
            exec:
              command:
                - wget
                - --spider
                - -q
                - localhost:8123/ping
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 5
          name: clickhouse
          ports:
            - containerPort: 9000
            - containerPort: 8123
          resources: {}
          volumeMounts:
            - mountPath: /etc/clickhouse-server/config.xml
              name: clickhouse-claim0
            - mountPath: /docker-entrypoint-initdb.d/init-db.sql
              name: clickhouse-claim1
            - mountPath: /var/lib/clickhouse/
              name: clickhouse-claim2
      restartPolicy: Always
      volumes:
        - name: clickhouse-claim0
          persistentVolumeClaim:
            claimName: clickhouse-claim0
        - name: clickhouse-claim1
          persistentVolumeClaim:
            claimName: clickhouse-claim1
        - name: clickhouse-claim2
          persistentVolumeClaim:
            claimName: clickhouse-claim2
status: {}
