apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/prometheus/alertmanager.yml
            - --storage.path=/data
          image: signoz/alertmanager:0.5.0
          name: alertmanager
          ports:
            - containerPort: 9093
          resources: {}
          volumeMounts:
            - mountPath: /prometheus/alertmanager.yml
              name: alertmanager-claim0
            - mountPath: /data
              name: alertmanager-claim1
      restartPolicy: Always
      volumes:
        - name: alertmanager-claim0
          persistentVolumeClaim:
            claimName: alertmanager-claim0
        - name: alertmanager-claim1
          persistentVolumeClaim:
            claimName: alertmanager-claim1
status: {}
