apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yaml
            - --mem-ballast-size-mib=683
          image: signoz/otelcontribcol:0.4.2
          name: otel-collector
          ports:
            - containerPort: 1777
            - containerPort: 8888
            - containerPort: 14268
            - containerPort: 55678
            - containerPort: 4317
            - containerPort: 13133
            - containerPort: 8889
          resources: {}
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yaml
              name: otel-collector-claim0
      restartPolicy: Always
      volumes:
        - name: otel-collector-claim0
          persistentVolumeClaim:
            claimName: otel-collector-claim0
status: {}
